package march3;

public class Exception {

	public static void main(String[] args) {
		// divide any value with zero
		try
		{
			int x=2564,y=0,z;
			z=x/y;
		System.out.println(z);
		}
		catch (Throwable y) {
			// TODO: handle exception
		}
	
		{
			System.out.println("y");
			//t.print stack trace();
		}
		//second block of code
		
		int a=2564,b=6,c;{
       c=a/b;
		System.out.println(c);
	}
	
	}
		
}	

	


